### ISSUE TITLE
decode GPS spoofed signal

### ISSUE THREAD

**Issue by truff77** [PierreAdams/HackRF-One-en-Francais#2]
Bonjour Pierre,
j'ai une capture (HackRF) d'un signal qui me semble être du spoofing de GPS et je dois décoder les coordonnées qui sont annoncées. 
J'ai aussi l'impression qu'il y avait du jamming de signal au milieu de tout cela. 
J'ai tout essayé avec gnss-sdr mais ne suis arrivé à rien pour le moment. Aurais-tu un conseil ? 

Merci d'avance !

**Comment by drive02** [comment]
Bonjour Pierre et Truff,
Je suis actuellement sur le même sujet sur root me et je n'arrive pas à lire le fichier comme je n'ai pas de hackrf one hardware sur moi. Normalement le challenge peut se faire sans matériel. Auriez vous une idée à me donner.

Merci d'avance ;)

**Comment by truff77** [comment]
Salut @drive02 
tu n'as pas besoin de hardware hackrf pour lire ce fichier et résoudre ce challenge. Cherche un tool qui permet de lire une capture de signal GPS et de le décoder. Il faudra bien le configurer. 

truff
